// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;

public class Boxtest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void boxtest1() {
    driver.get("https://www.selenium.dev/selenium/web/dynamic.html");
    driver.manage().window().setSize(new Dimension(1900, 1060));
    driver.findElement(By.id("adder")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.className("box0")));
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#box0"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.id("reveal")).click();
    driver.findElement(By.id("revealed")).click();
    driver.findElement(By.id("revealed")).sendKeys("Box test");
    driver.findElement(By.id("revealed")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("body")).click();
  }
}
